/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ICpinSppStaking,
  ICpinSppStakingInterface,
} from "../../../contracts/interfaces/ICpinSppStaking";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "sppId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "didAccountPubKey",
        type: "uint256",
      },
    ],
    name: "DidRegistered",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "sppId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "didAccountPubKey",
        type: "uint256",
      },
    ],
    name: "DidUnregistered",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "sppId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "timestamp",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "productionW",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "cdataAmount",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "cwattAmount",
        type: "uint128",
      },
    ],
    name: "ProductionInfoAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "sppId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "cdataAmount",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "cwattAmount",
        type: "uint128",
      },
    ],
    name: "RewardCollected",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "sppId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "startTime",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "string",
        name: "infoIpfsCid",
        type: "string",
      },
    ],
    name: "SppCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "sppId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "ipfsCid",
        type: "string",
      },
    ],
    name: "SppIpfsCidUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "sppId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "capacity",
        type: "uint128",
      },
    ],
    name: "TokenStaked",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "sppId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "capacity",
        type: "uint128",
      },
    ],
    name: "TokenWithdrawn",
    type: "event",
  },
  {
    inputs: [],
    name: "CDATAToken",
    outputs: [
      {
        internalType: "contract IERC20",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "CWATTToken",
    outputs: [
      {
        internalType: "contract IERC20",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "sppId",
        type: "uint256",
      },
      {
        internalType: "uint32",
        name: "startTime",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "maxCapacity",
        type: "uint32",
      },
      {
        internalType: "string",
        name: "infoIpfsCid",
        type: "string",
      },
    ],
    name: "addSpp",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "sppId",
        type: "uint256",
      },
      {
        internalType: "uint32",
        name: "previousUpdateTime",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "timestamp",
        type: "uint32",
      },
      {
        internalType: "uint128",
        name: "productionW",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "cdataAmount",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "cwattAmount",
        type: "uint128",
      },
    ],
    name: "addSppProductionInfo",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "sppId",
        type: "uint256",
      },
    ],
    name: "calculateRewardsEarned",
    outputs: [
      {
        internalType: "uint128",
        name: "earnedCdata",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "earnedCwatt",
        type: "uint128",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "collectReward",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "sppId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
    ],
    name: "getSppDidByIndex",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "sppId",
        type: "uint256",
      },
    ],
    name: "getSppDidCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "nft",
    outputs: [
      {
        internalType: "contract ICpinVirtualPanel",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "operator",
        type: "address",
      },
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "onERC721Received",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "sppId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "didAccountPubKey",
        type: "uint256",
      },
    ],
    name: "registerDid",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "sppId",
        type: "uint256",
      },
    ],
    name: "sppDatas",
    outputs: [
      {
        internalType: "uint128",
        name: "totalStakedCapacity",
        type: "uint128",
      },
      {
        internalType: "uint32",
        name: "startTime",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "numberOfStakes",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "lastUpdateTime",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "maxCapacity",
        type: "uint32",
      },
      {
        internalType: "uint128",
        name: "rewardIndexCDATA",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "rewardIndexCWATT",
        type: "uint128",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "sppId",
        type: "uint256",
      },
    ],
    name: "sppIpfsCids",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "sppId",
        type: "uint256",
      },
    ],
    name: "tokenEarnedValues",
    outputs: [
      {
        internalType: "uint128",
        name: "valueCDATA",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "valueCWATT",
        type: "uint128",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "tokenIdToSppId",
    outputs: [
      {
        internalType: "uint256",
        name: "sppId",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
    ],
    name: "tokenOfOwnerByIndex",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "sppId",
        type: "uint256",
      },
    ],
    name: "tokenRewardIndexes",
    outputs: [
      {
        internalType: "uint128",
        name: "valueCDATA",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "valueCWATT",
        type: "uint128",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "sppId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "didAccountPubKey",
        type: "uint256",
      },
    ],
    name: "unregisterDid",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "sppId",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "ipfsCid",
        type: "string",
      },
    ],
    name: "updateSppIpfsCid",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "withdrawToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ICpinSppStaking__factory {
  static readonly abi = _abi;
  static createInterface(): ICpinSppStakingInterface {
    return new utils.Interface(_abi) as ICpinSppStakingInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICpinSppStaking {
    return new Contract(address, _abi, signerOrProvider) as ICpinSppStaking;
  }
}
