/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ICpinSppStaking__factory } from "./ICpinSppStaking__factory";
export { ICpinVirtualPanel__factory } from "./ICpinVirtualPanel__factory";
export { INonTransferrableToken__factory } from "./INonTransferrableToken__factory";
export { IReleaseToken__factory } from "./IReleaseToken__factory";
