/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ICpinSppStaking } from "./ICpinSppStaking";
export type { ICpinVirtualPanel } from "./ICpinVirtualPanel";
export type { INonTransferrableToken } from "./INonTransferrableToken";
export type { IReleaseToken } from "./IReleaseToken";
